name: Test
on: [push]
env:
  python_version: "3.10"
  runs-on: ubuntu-latest

jobs:
  call-workflow-passing-data:
    uses: ./.github/worksflows/reusable/reusable_unittests.yml
    with:
      python_version: ${{ env.python_version }}
      runs-on: ${{ env.runs-on }}
      
