name: Unittests
on: [push]
env:
  PYTHON_VERSION: "3.10"
  RUNS_ON: "ubuntu-latest"

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_unittests.yml
    with:
      python_version: $PYTHON_VERSION
      runs-on: $RUNS_ON
      
